install.packages("ScottKnottESD")
library(ScottKnottESD)
par(mfrow=c(2,3))
sk <- sk_esd(f_measure_Rank)
plot(sk,xlab="(a) F-measure",ylab="Ranking")
sk <- sk_esd(Balance_Rank)
plot(sk,xlab="(b) Balance",ylab="Ranking")
sk <- sk_esd(g_measure_Rank)
plot(sk,xlab="(c) G-measure",ylab="Ranking")
sk <- sk_esd(MCC_Rank)
plot(sk,xlab="(d) MCC",ylab="Ranking")
sk <- sk_esd(AUC_Rank)
plot(sk,xlab="(d) AUC",ylab="Ranking")
